### ISSUE TITLE
daytona project-config feature explained

### ISSUE THREAD

**Issue by nkkko** [daytonaio/content#33]
### Content Type

Article

### Article Description

Write an article to introduce a daytona project-config feature. Use up to 2 screenshots, code snippets and sample repo (can be existing one) for which you will create project-config.

### Target Audience

individual dev

**Comment by nkkko** [comment]
@Niharika0104 any updates?

**Comment by Niharika0104** [comment]
@nkkko I'm having trouble starting a workspace using a Git repo URL. The Git repo has a working devcontainer setup, and it functions perfectly within the repository itself. However, when I try to run the same setup from a Daytona workspace, I'm encountering errors.
this is the command I used dtn create <gitrepo> --builder=auto
Since I need add some attachments in the content.I need atleast one workspace to be created and running.

**Comment by bryans-go** [comment]
/attempt #33

<div id="algora-attempt" />

| [Algora profile](https://console.algora.io/@/bryans-go) | Completed bounties | Tech | Active attempts | Options |
| --- | --- | --- | --- | --- |
| @bryans-go | 1 daytonaio bounty | <div align="center"></div> | <div align="center"></div> | [Cancel attempt](https://console.algora.io/api/bounties/cm02k2gdk000wl503sfhihodh/cancel-attempt) |
